# Generated by Django 4.0.1 on 2022-01-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subs', '0002_alter_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='period',
            field=models.PositiveIntegerField(choices=[(1, 1), (3, 3), (6, 6), (12, 12)], default=12),
        ),
    ]
